CREATE TABLE IF NOT EXISTS prefixes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    prefix TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS suffixes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    suffix TEXT UNIQUE
);
